server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
management:
  info:
    env.enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
info:
  app.name: AlgaShop Service Registry

#logging:
  #level:
    #com.netflix.discovery.DiscoveryClient: OFF
    #com.netflix.discovery: OFF
    #com.netflix.eureka: OFF